// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_bthm_H_GEN_
#define RCPP_bthm_H_GEN_

#include "bthm_RcppExports.h"

#endif // RCPP_bthm_H_GEN_
