// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_bthm_RCPPEXPORTS_H_GEN_
#define RCPP_bthm_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace bthm {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("bthm", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("bthm", "_bthm_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in bthm");
            }
        }
    }

    inline List BTHMRcpp(NumericVector y_, NumericVector a_, NumericVector w_, NumericVector x_con_, NumericVector x_mod_, NumericVector x_coxcon_, NumericVector m_, NumericVector status_, List x_con_info_list, List x_mod_info_list, List x_coxcon_info_list, NumericVector intv_, int burn, int nd, int thin, int ntree_coxcon, int ntree_mod, int ntree_con, double nu, double con_alpha, double con_beta, double mod_alpha, double mod_beta, double coxcon_alpha, double coxcon_beta, NumericVector kappa_, NumericVector sigest_, NumericVector zeta_, NumericVector truehzd_, NumericVector hcsig_coxcon_, NumericVector hcsig_mod_, CharacterVector treef_con_name_, CharacterVector treef_mod_name_, CharacterVector treef_coxcon_name_, double t_survp, int printevery = 100, double trt_init = 1.0, int nknots = 20, bool verbose_sigma = false, bool vs = false) {
        typedef SEXP(*Ptr_BTHMRcpp)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_BTHMRcpp p_BTHMRcpp = NULL;
        if (p_BTHMRcpp == NULL) {
            validateSignature("List(*BTHMRcpp)(NumericVector,NumericVector,NumericVector,NumericVector,NumericVector,NumericVector,NumericVector,NumericVector,List,List,List,NumericVector,int,int,int,int,int,int,double,double,double,double,double,double,double,NumericVector,NumericVector,NumericVector,NumericVector,NumericVector,NumericVector,CharacterVector,CharacterVector,CharacterVector,double,int,double,int,bool,bool)");
            p_BTHMRcpp = (Ptr_BTHMRcpp)R_GetCCallable("bthm", "_bthm_BTHMRcpp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_BTHMRcpp(Shield<SEXP>(Rcpp::wrap(y_)), Shield<SEXP>(Rcpp::wrap(a_)), Shield<SEXP>(Rcpp::wrap(w_)), Shield<SEXP>(Rcpp::wrap(x_con_)), Shield<SEXP>(Rcpp::wrap(x_mod_)), Shield<SEXP>(Rcpp::wrap(x_coxcon_)), Shield<SEXP>(Rcpp::wrap(m_)), Shield<SEXP>(Rcpp::wrap(status_)), Shield<SEXP>(Rcpp::wrap(x_con_info_list)), Shield<SEXP>(Rcpp::wrap(x_mod_info_list)), Shield<SEXP>(Rcpp::wrap(x_coxcon_info_list)), Shield<SEXP>(Rcpp::wrap(intv_)), Shield<SEXP>(Rcpp::wrap(burn)), Shield<SEXP>(Rcpp::wrap(nd)), Shield<SEXP>(Rcpp::wrap(thin)), Shield<SEXP>(Rcpp::wrap(ntree_coxcon)), Shield<SEXP>(Rcpp::wrap(ntree_mod)), Shield<SEXP>(Rcpp::wrap(ntree_con)), Shield<SEXP>(Rcpp::wrap(nu)), Shield<SEXP>(Rcpp::wrap(con_alpha)), Shield<SEXP>(Rcpp::wrap(con_beta)), Shield<SEXP>(Rcpp::wrap(mod_alpha)), Shield<SEXP>(Rcpp::wrap(mod_beta)), Shield<SEXP>(Rcpp::wrap(coxcon_alpha)), Shield<SEXP>(Rcpp::wrap(coxcon_beta)), Shield<SEXP>(Rcpp::wrap(kappa_)), Shield<SEXP>(Rcpp::wrap(sigest_)), Shield<SEXP>(Rcpp::wrap(zeta_)), Shield<SEXP>(Rcpp::wrap(truehzd_)), Shield<SEXP>(Rcpp::wrap(hcsig_coxcon_)), Shield<SEXP>(Rcpp::wrap(hcsig_mod_)), Shield<SEXP>(Rcpp::wrap(treef_con_name_)), Shield<SEXP>(Rcpp::wrap(treef_mod_name_)), Shield<SEXP>(Rcpp::wrap(treef_coxcon_name_)), Shield<SEXP>(Rcpp::wrap(t_survp)), Shield<SEXP>(Rcpp::wrap(printevery)), Shield<SEXP>(Rcpp::wrap(trt_init)), Shield<SEXP>(Rcpp::wrap(nknots)), Shield<SEXP>(Rcpp::wrap(verbose_sigma)), Shield<SEXP>(Rcpp::wrap(vs)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

}

#endif // RCPP_bthm_RCPPEXPORTS_H_GEN_
