# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BTHMRcpp <- function(y_, a_, w_, x_con_, x_mod_, x_coxcon_, m_, status_, x_con_info_list, x_mod_info_list, x_coxcon_info_list, intv_, burn, nd, thin, ntree_coxcon, ntree_mod, ntree_con, nu, con_alpha, con_beta, mod_alpha, mod_beta, coxcon_alpha, coxcon_beta, kappa_, sigest_, zeta_, truehzd_, hcsig_coxcon_, hcsig_mod_, treef_con_name_, treef_mod_name_, treef_coxcon_name_, t_survp, printevery = 100L, trt_init = 1.0, nknots = 20L, verbose_sigma = FALSE, vs = FALSE) {
    .Call('_bthm_BTHMRcpp', PACKAGE = 'bthm', y_, a_, w_, x_con_, x_mod_, x_coxcon_, m_, status_, x_con_info_list, x_mod_info_list, x_coxcon_info_list, intv_, burn, nd, thin, ntree_coxcon, ntree_mod, ntree_con, nu, con_alpha, con_beta, mod_alpha, mod_beta, coxcon_alpha, coxcon_beta, kappa_, sigest_, zeta_, truehzd_, hcsig_coxcon_, hcsig_mod_, treef_con_name_, treef_mod_name_, treef_coxcon_name_, t_survp, printevery, trt_init, nknots, verbose_sigma, vs)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_bthm_RcppExport_registerCCallable', PACKAGE = 'bthm')
})
